title: <p align="center"> Swapnil Athawale </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/swapnil-athawale/">LinkedIn</a> |
  <a href="https://github.com/swapnil-athawale">GitHub</a>
  </p>
  
  <p align="justify">
  Data Science Engineer with 2 years of professional experience.
  <br><br>
  With strong technical background in machine learning and software engineering.
Proficient in predictive modeling, computer vision and data processing to solve challenging business problems.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
